# Generated by Django 4.2.2 on 2023-06-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_rename_post_advertisementcategory_advertisement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("TA", "Танки"),
                    ("HI", "Хилы"),
                    ("DD", "ДД"),
                    ("TR", "Торговцы"),
                    ("GD", "Гилдмастеры"),
                    ("GD", "Квестгиверы"),
                    ("QG", "Уборщик"),
                    ("BS", "Кузнецы"),
                    ("TN", "Кожевники"),
                    ("CO", "Зельевары"),
                    ("MA", "Мастера заклинаний"),
                ],
                default="MA",
                max_length=2,
                unique=True,
            ),
        ),
    ]
