# Generated by Django 4.2.2 on 2023-06-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_feedback_accepted_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="rating",
        ),
    ]
